import type { MarketplaceProduct } from './api';

type RawProduct = MarketplaceProduct & {
  category: string; ingredients: string[]; ai_reason: string;
  concern_flags: string[]; attributes: string[];
};

const allProducts: RawProduct[] = [
  {"name":"Effaclar Duo+M","brand":"LA ROCHE-POSAY","category":"Treatment","price":24.99,"ingredients":["Aqua","Glycerin","Dimethicone","Niacinamide","Isocetyl Stearate","Salicylic Acid","Zinc PCA","Linoleic Acid","Ceramide NP","Piroctone Olamine","Silica","Xanthan Gum"],"match_score":97,"reason":"Contains Salicylic Acid and Niacinamide in the top 6 ingredients to directly target active breakouts while Zinc PCA regulates sebum production.","concern_flag":null,"attributes":["Non-Comedogenic","Oil-Free","Paraben-Free"],"concern_flags":[],"ai_reason":"Contains Salicylic Acid and Niacinamide in the top 6 ingredients to directly target active breakouts while Zinc PCA regulates sebum production."},
  {"name":"Foaming Facial Cleanser","brand":"CERAVE","category":"Cleansers","price":12.99,"ingredients":["Aqua","Cocamidopropyl Hydroxysultaine","Glycerin","Niacinamide","Ceramide NP","Ceramide AP","Ceramide EOP","Hyaluronic Acid","Sodium Lauroyl Sarcosinate","Cholesterol","Phenoxyethanol"],"match_score":92,"reason":"Ceramides and Hyaluronic Acid reinforce the skin barrier while Niacinamide helps calm redness — ideal for compromised moisture barrier repair.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Paraben-Free","Ceramide-Infused"],"concern_flags":[],"ai_reason":"Ceramides and Hyaluronic Acid reinforce the skin barrier while Niacinamide helps calm redness — ideal for compromised moisture barrier repair."},
  {"name":"Niacinamide 10% + Zinc 1%","brand":"THE ORDINARY","category":"Treatment","price":14.99,"ingredients":["Aqua","Niacinamide","Pentylene Glycol","Zinc PCA","Tamarindus Indica Seed Gum","Xanthan Gum","Phenoxyethanol","Ethylhexylglycerin"],"match_score":98,"reason":"10% Niacinamide paired with Zinc PCA directly targets excess sebum and enlarged pores — perfectly aligned with oily, acne-prone skin goals.","concern_flag":null,"attributes":["Oil-Free","Alcohol-Free","Paraben-Free","Vegan"],"concern_flags":[],"ai_reason":"10% Niacinamide paired with Zinc PCA directly targets excess sebum and enlarged pores — perfectly aligned with oily, acne-prone skin goals."},
  {"name":"Skin Perfecting 2% BHA Liquid Exfoliant","brand":"PAULA'S CHOICE","category":"Treatment","price":31.99,"ingredients":["Aqua","Methylpropanediol","Butylene Glycol","Salicylic Acid","Camellia Oleifera Leaf Extract","Sodium Hydroxide","Polysorbate 20","Tocopherol","Panthenol","Xanthan Gum"],"match_score":96,"reason":"2% Salicylic Acid in a leave-on formula penetrates deep into pores to dissolve congestion and prevent future breakouts — a top-tier acne treatment.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic","Dye-Free"],"concern_flags":[],"ai_reason":"2% Salicylic Acid in a leave-on formula penetrates deep into pores to dissolve congestion and prevent future breakouts — a top-tier acne treatment."},
  {"name":"Advanced Snail 96 Mucin Power Essence","brand":"COSRX","category":"Treatment","price":29.99,"ingredients":["Snail Secretion Filtrate","Betaine","Butylene Glycol","1,2-Hexanediol","Sodium Hyaluronate","Panthenol","Allantoin","Ethylhexylglycerin","Carbomer"],"match_score":88,"reason":"Snail mucin combined with Panthenol and Allantoin accelerates scar healing and calms inflammation — excellent for post-acne redness and scarring.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Cruelty-Free"],"concern_flags":[],"ai_reason":"Snail mucin combined with Panthenol and Allantoin accelerates scar healing and calms inflammation — excellent for post-acne redness and scarring."},
  {"name":"Cicaplast Baume B5+","brand":"LA ROCHE-POSAY","category":"Moisturizers","price":27.99,"ingredients":["Aqua","Hydrogenated Polyisobutene","Dimethicone","Glycerin","Panthenol","Butyrospermum Parkii Butter","Madecassoside","Zinc Gluconate","Copper Gluconate","Manganese Gluconate"],"match_score":91,"reason":"Panthenol and Madecassoside work synergistically to repair irritated skin while Shea Butter provides deep moisture without clogging pores.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Soothing"],"concern_flags":[],"ai_reason":"Panthenol and Madecassoside work synergistically to repair irritated skin while Shea Butter provides deep moisture without clogging pores."},
  {"name":"Moisturizing Cream","brand":"CERAVE","category":"Moisturizers","price":16.99,"ingredients":["Aqua","Glycerin","Cetearyl Alcohol","Caprylic/Capric Triglyceride","Ceramide NP","Ceramide AP","Ceramide EOP","Cetyl Alcohol","Petrolatum","Hyaluronic Acid","Cholesterol","Carbomer"],"match_score":85,"reason":"Three essential ceramides and Hyaluronic Acid restore the lipid barrier and lock in hydration — best for dry, compromised, or sensitive skin types.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Paraben-Free","Ceramide-Infused"],"concern_flags":[],"ai_reason":"Three essential ceramides and Hyaluronic Acid restore the lipid barrier and lock in hydration — best for dry, compromised, or sensitive skin types."},
  {"name":"Unseen Sunscreen SPF 40","brand":"SUPERGOOP","category":"Sunscreen","price":34.99,"ingredients":["Dimethicone","Isononyl Isononanoate","Polysilicone-15","Butyloctyl Salicylate","Diethylamino Hydroxybenzoyl Hexyl Benzoate","Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine","Methylene Bis-Benzotriazolyl Tetramethylbutylphenol","Tocopherol","Glycerin"],"match_score":93,"reason":"Weightless chemical sunscreen with a primer-like finish that protects against UVA/UVB without any white cast — perfect for daily wear over treatment products.","concern_flag":null,"attributes":["Fragrance-Free","Oil-Free","Non-Comedogenic","Water-Resistant"],"concern_flags":[],"ai_reason":"Weightless chemical sunscreen with a primer-like finish that protects against UVA/UVB without any white cast — perfect for daily wear over treatment products."},
  {"name":"Azelaic Acid Suspension 10%","brand":"THE ORDINARY","category":"Treatment","price":18.99,"ingredients":["Aqua","Isodecyl Neopentanoate","Dimethicone","Azelaic Acid","Dimethicone Crosspolymer","Isohexadecane","Silicone Crosspolymer","Tocopherol","Triethanolamine"],"match_score":94,"reason":"10% Azelaic Acid targets both acne and hyperpigmentation while calming redness — a dual-action ingredient for post-inflammatory erythema and blemishes.","concern_flag":null,"attributes":["Oil-Free","Alcohol-Free","Vegan","Cruelty-Free"],"concern_flags":[],"ai_reason":"10% Azelaic Acid targets both acne and hyperpigmentation while calming redness — a dual-action ingredient for post-inflammatory erythema and blemishes."},
  {"name":"C-Firma Fresh Day Serum","brand":"DRUNK ELEPHANT","category":"Treatment","price":78.99,"ingredients":["Aqua","Ascorbyl Glucoside","Glycerin","Sodium Hyaluronate Crosspolymer","Lactobacillus/Pumpkin Ferment Extract","Tocopherol","Ferulic Acid","Superoxide Dismutase","Tripeptide-1"],"match_score":82,"reason":"Stabilized Vitamin C derivative paired with Ferulic Acid brightens hyperpigmentation and evens skin tone — most effective for dullness and dark spots.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Silicone-Free"],"concern_flags":[],"ai_reason":"Stabilized Vitamin C derivative paired with Ferulic Acid brightens hyperpigmentation and evens skin tone — most effective for dullness and dark spots."},
  {"name":"Green Tea Seed Hyaluronic Serum","brand":"INNISFREE","category":"Treatment","price":22.99,"ingredients":["Camellia Sinensis Leaf Water","Aqua","Glycerin","Butylene Glycol","Camellia Sinensis Seed Oil","Sodium Hyaluronate","Propanediol","Panthenol","Betaine","Carbomer"],"match_score":79,"reason":"Antioxidant-rich fermented green tea water provides deep hydration while Sodium Hyaluronate plumps the skin — suitable for dehydrated, sensitive skin.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Antioxidant-rich fermented green tea water provides deep hydration while Sodium Hyaluronate plumps the skin — suitable for dehydrated, sensitive skin."},
  {"name":"Hydrating Facial Cleanser","brand":"CERAVE","category":"Cleansers","price":11.99,"ingredients":["Aqua","Glycerin","Cetearyl Alcohol","Caprylic/Capric Triglyceride","Cetyl Alcohol","Ceramide NP","Ceramide AP","Ceramide EOP","Peg-40 Stearate","Hyaluronic Acid","Cholesterol","Xanthan Gum"],"match_score":87,"reason":"Non-foaming cream cleanser with Ceramides and Hyaluronic Acid that cleanses without stripping — excellent for compromised or dry sensitive skin types.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Paraben-Free"],"concern_flags":[],"ai_reason":"Non-foaming cream cleanser with Ceramides and Hyaluronic Acid that cleanses without stripping — excellent for compromised or dry sensitive skin types."},
  {"name":"Matcha Hemp Hydrating Cleanser","brand":"KRAVE BEAUTY","category":"Cleansers","price":23.99,"ingredients":["Aqua","Glycerin","Coconut Acid","Potassium Hydroxide","Hemp Seed Oil","Camellia Sinensis Leaf Powder","Panthenol","Allantoin","Calendula Officinalis Extract"],"match_score":84,"reason":"Low-foaming gel cleanser with antioxidant-rich Matcha and Hemp Seed Oil that calms inflammation while gently cleansing — great for redness-prone skin.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Vegan"],"concern_flags":[],"ai_reason":"Low-foaming gel cleanser with antioxidant-rich Matcha and Hemp Seed Oil that calms inflammation while gently cleansing — great for redness-prone skin."},
  {"name":"Hydro Boost Water Gel","brand":"NEUTROGENA","category":"Moisturizers","price":21.49,"ingredients":["Aqua","Dimethicone","Glycerin","Dimethicone/Vinyl Dimethicone Crosspolymer","Sodium Hyaluronate","Phenoxyethanol","Polyacrylamide","C13-14 Isoparaffin","Laureth-7"],"match_score":76,"reason":"Oil-free gel moisturizer with Hyaluronic Acid delivers a hydration burst without heaviness — adequate for normal skin but lacks barrier-repair lipids.","concern_flag":"Contains Fragrance","attributes":["Non-Comedogenic","Oil-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Oil-free gel moisturizer with Hyaluronic Acid delivers a hydration burst without heaviness — adequate for normal skin but lacks barrier-repair lipids."},
  {"name":"CALM Redness Relief Moisturizer","brand":"PAULA'S CHOICE","category":"Moisturizers","price":29.99,"ingredients":["Aqua","Glycerin","Caprylic/Capric Triglyceride","Cetearyl Alcohol","Allantoin","Sodium Hyaluronate","Ceramide NP","Glycyrrhiza Glabra Root Extract","Aloe Barbadensis Leaf Juice","Tocopherol"],"match_score":95,"reason":"Licorice root extract and Allantoin actively reduce visible redness while Ceramides repair the skin barrier — purpose-built for sensitive, reactive skin.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic","For Sensitive Skin"],"concern_flags":[],"ai_reason":"Licorice root extract and Allantoin actively reduce visible redness while Ceramides repair the skin barrier — purpose-built for sensitive, reactive skin."},
  {"name":"Gentle Skin Cleanser","brand":"CETAPHIL","category":"Cleansers","price":13.99,"ingredients":["Aqua","Cetyl Alcohol","Propylene Glycol","Sodium Lauryl Sulfate","Stearyl Alcohol","Methylparaben","Propylparaben","Butylparaben"],"match_score":68,"reason":"Classic gentle cleanser that effectively removes impurities without stripping the skin, but the parabens and SLS may be irritating for very reactive skin.","concern_flag":"Contains Parabens","attributes":["Fragrance-Free","Non-Comedogenic"],"concern_flags":["Contains Parabens","Contains Sulfates"],"ai_reason":"Classic gentle cleanser that effectively removes impurities without stripping the skin, but the parabens and SLS may be irritating for very reactive skin."},
  {"name":"Glycolic Acid 7% Exfoliating Toner","brand":"THE ORDINARY","category":"Treatment","price":15.99,"ingredients":["Aqua","Glycolic Acid","Rosa Damascena Flower Water","Centaurea Cyanus Flower Water","Propanediol","Panthenol","Triethanolamine","Allantoin","Aloe Barbadensis Leaf Juice","Tocopherol"],"match_score":86,"reason":"7% Glycolic Acid provides chemical exfoliation that smooths texture and fades hyperpigmentation over time — best for dull or sun-damaged skin.","concern_flag":null,"attributes":["Alcohol-Free","Paraben-Free","Vegan","Cruelty-Free"],"concern_flags":[],"ai_reason":"7% Glycolic Acid provides chemical exfoliation that smooths texture and fades hyperpigmentation over time — best for dull or sun-damaged skin."},
  {"name":"UV Clear Broad-Spectrum SPF 46","brand":"ELTA MD","category":"Sunscreen","price":39.99,"ingredients":["Purified Water","Zinc Oxide","Niacinamide","Octyl Methoxycinnamate","Lactic Acid","Hyaluronic Acid","Tocopherol","Panthenol"],"match_score":97,"reason":"Niacinamide-infused mineral sunscreen that protects against UV damage while actively treating acne and hyperpigmentation — a multi-functional daily essential.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Oil-Free","Paraben-Free"],"concern_flags":[],"ai_reason":"Niacinamide-infused mineral sunscreen that protects against UV damage while actively treating acne and hyperpigmentation — a multi-functional daily essential."},
  {"name":"Squalane + Probiotic Gel Moisturizer","brand":"BIOSSANCE","category":"Moisturizers","price":52.99,"ingredients":["Aqua","Squalane","Glycerin","Pentylene Glycol","Lactobacillus Ferment","Sodium Hyaluronate","Oryza Sativa Bran Extract","Panthenol","Ceramide NP","Sodium PCA"],"match_score":89,"reason":"Squalane mimics the skin's natural sebum while probiotics support the microbiome — ideal for balancing combination skin without triggering breakouts.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Cruelty-Free","Vegan"],"concern_flags":[],"ai_reason":"Squalane mimics the skin's natural sebum while probiotics support the microbiome — ideal for balancing combination skin without triggering breakouts."},
  {"name":"Discoloration Correcting Serum","brand":"GOOD MOLECULES","category":"Treatment","price":26.99,"ingredients":["Aqua","Butylene Glycol","Tranexamic Acid","Niacinamide","Glycerin","Sodium Hyaluronate","Ascorbyl Glucoside","Phenoxyethanol","Ethylhexylglycerin"],"match_score":93,"reason":"Tranexamic Acid combined with Niacinamide and Vitamin C targets stubborn hyperpigmentation from multiple pathways — highly effective for post-acne marks.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Vegan"],"concern_flags":[],"ai_reason":"Tranexamic Acid combined with Niacinamide and Vitamin C targets stubborn hyperpigmentation from multiple pathways — highly effective for post-acne marks."},
  {"name":"Toleriane Double Repair Face Moisturizer","brand":"LA ROCHE-POSAY","category":"Moisturizers","price":23.99,"ingredients":["Aqua","Dimethicone","Glycerin","Squalane","Ceramide NP","Niacinamide","Allantoin","Aloe Barbadensis Leaf Juice","Tocopherol"],"match_score":90,"reason":"Prebiotic thermal water, Ceramides, and Niacinamide work together to restore the skin barrier and soothe irritation — excellent for sensitive, allergy-prone skin.","concern_flag":null,"attributes":["Fragrance-Free","Non-Comedogenic","Paraben-Free"],"concern_flags":[],"ai_reason":"Prebiotic thermal water, Ceramides, and Niacinamide work together to restore the skin barrier and soothe irritation — excellent for sensitive, allergy-prone skin."},
  {"name":"Perfect UV Sunscreen Mild Milk SPF 50+","brand":"ANESSA","category":"Sunscreen","price":31.99,"ingredients":["Water","Zinc Oxide","Titanium Dioxide","Dimethicone","Cetyl Ethylhexanoate","Glycerin","Peg-60 Hydrogenated Castor Oil","Tocopherol","Aloe Barbadensis Leaf Extract"],"match_score":91,"reason":"100% mineral UV filter formula designed specifically for sensitive skin — Zinc Oxide and Titanium Dioxide provide broad-spectrum protection without chemical irritants.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Alcohol-Free","For Sensitive Skin"],"concern_flags":[],"ai_reason":"100% mineral UV filter formula designed specifically for sensitive skin — Zinc Oxide and Titanium Dioxide provide broad-spectrum protection without chemical irritants."},
  {"name":"Salicylic Acid Daily Gentle Cleanser","brand":"COSRX","category":"Cleansers","price":14.99,"ingredients":["Aqua","Sodium Lauryl Sulfate","Cocamidopropyl Betaine","Salicylic Acid","Melaleuca Alternifolia Leaf Oil","Allantoin","Panthenol","Butylene Glycol"],"match_score":95,"reason":"0.5% Salicylic Acid in a daily cleanser gently exfoliates pores without over-drying — a staple morning cleanse for maintaining clear, blemish-free skin.","concern_flag":"Contains Sulfates","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Sulfates"],"ai_reason":"0.5% Salicylic Acid in a daily cleanser gently exfoliates pores without over-drying — a staple morning cleanse for maintaining clear, blemish-free skin."},
  {"name":"Centella Green Level Buffet Serum","brand":"PURITO","category":"Treatment","price":25.99,"ingredients":["Centella Asiatica Extract","Aqua","Butylene Glycol","Glycerin","Niacinamide","Sodium Hyaluronate","Madecassoside","Panthenol","Allantoin","Betaine"],"match_score":96,"reason":"Centella Asiatica is the #1 ingredient with Madecassoside to calm inflammation and repair the skin barrier — purpose-formulated for redness and sensitivity.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Vegan"],"concern_flags":[],"ai_reason":"Centella Asiatica is the #1 ingredient with Madecassoside to calm inflammation and repair the skin barrier — purpose-formulated for redness and sensitivity."},
  {"name":"Ultra Sheer Dry-Touch SPF 70","brand":"NEUTROGENA","category":"Sunscreen","price":14.99,"ingredients":["Aqua","Homosalate","Octocrylene","Ethylhexyl Salicylate","Butyl Methoxydibenzoylmethane","Dimethicone","Acrylates Copolymer","Tocopherol","Panthenol"],"match_score":72,"reason":"High SPF 70 protection in a Dry-Touch format that won't feel greasy, but the chemical UV filter cocktail may cause stinging on very sensitive or barrier-damaged skin.","concern_flag":"Contains Alcohol","attributes":["Non-Comedogenic","Water-Resistant"],"concern_flags":["Contains Alcohol Denat"],"ai_reason":"High SPF 70 protection in a Dry-Touch format that won't feel greasy, but the chemical UV filter cocktail may cause stinging on very sensitive or barrier-damaged skin."},
  {"name":"Purity Made Simple One-Step Facial Cleanser","brand":"PHILOSOPHY","category":"Cleansers","price":28.99,"ingredients":["Aqua","Sodium C14-16 Olefin Sulfonate","Cocamidopropyl Betaine","Glycerin","Hexylene Glycol","Chamomilla Recutita Flower Extract","Aloe Barbadensis Leaf Juice","Salicylic Acid","Tocopherol"],"match_score":74,"reason":"Multi-tasking cleanser that removes makeup while gently exfoliating, but the strong surfactant base may disrupt the moisture barrier in already compromised skin.","concern_flag":null,"attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":[],"ai_reason":"Multi-tasking cleanser that removes makeup while gently exfoliating, but the strong surfactant base may disrupt the moisture barrier in already compromised skin."},
  {"name":"Polyglutamic Acid Dewy Sunscreen SPF 30","brand":"THE INKEY LIST","category":"Sunscreen","price":18.99,"ingredients":["Aqua","Homosalate","Ethylhexyl Salicylate","Butyloctyl Salicylate","Polyglutamic Acid","Glycerin","Niacinamide","Panthenol","Tocopherol"],"match_score":78,"reason":"Polyglutamic Acid provides superior hydration retention compared to Hyaluronic Acid while SPF 30 protects daily — a solid everyday maintenance sunscreen.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free","Vegan"],"concern_flags":["Contains Fragrance"],"ai_reason":"Polyglutamic Acid provides superior hydration retention compared to Hyaluronic Acid while SPF 30 protects daily — a solid everyday maintenance sunscreen."},
  {"name":"Beste No. 9 Jelly Cleanser","brand":"DRUNK ELEPHANT","category":"Cleansers","price":34.99,"ingredients":["Aqua","Glycerin","Cocamidopropyl Betaine","Sodium Cocoyl Amino Acids","Lactobacillus/Pumpkin Ferment Extract","Panthenol","Ceramide NP","Aloe Barbadensis Leaf Juice","Phenoxyethanol"],"match_score":80,"reason":"pH-balanced jelly cleanser with gentle surfactants and Ceramides that cleanses without stripping — a universally safe option but lacks targeted treatment benefits.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Sulfate-Free"],"concern_flags":[],"ai_reason":"pH-balanced jelly cleanser with gentle surfactants and Ceramides that cleanses without stripping — a universally safe option but lacks targeted treatment benefits."},
  {"name":"C E Ferulic","brand":"SKINCEUTICALS","category":"Treatment","price":169.99,"ingredients":["Aqua","Ascorbic Acid","Glycerin","Propylene Glycol","Tocopherol","Ferulic Acid","Phenoxyethanol","Panthenol","Sodium Hyaluronate"],"match_score":85,"reason":"Gold-standard 15% Vitamin C with Ferulic Acid provides potent antioxidant protection and visible brightening — unmatched for photoaging and hyperpigmentation correction.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free"],"concern_flags":[],"ai_reason":"Gold-standard 15% Vitamin C with Ferulic Acid provides potent antioxidant protection and visible brightening — unmatched for photoaging and hyperpigmentation correction."},
  {"name":"Resurfacing Retinol Serum","brand":"CERAVE","category":"Treatment","price":21.99,"ingredients":["Aqua","Glycerin","Dimethicone","Encapsulated Retinol","Ceramide NP","Ceramide AP","Ceramide EOP","Niacinamide","Licorice Root Extract","Hyaluronic Acid","Cholesterol"],"match_score":88,"reason":"Encapsulated Retinol with three Ceramides and Licorice Root Extract resurfaces skin texture and fades marks while the delivery system minimizes irritation.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic"],"concern_flags":[],"ai_reason":"Encapsulated Retinol with three Ceramides and Licorice Root Extract resurfaces skin texture and fades marks while the delivery system minimizes irritation."},
  {"name":"Anthelios Melt-in Milk Sunscreen SPF 100","brand":"LA ROCHE-POSAY","category":"Sunscreen","price":35.99,"ingredients":["Aqua","Homosalate","Octocrylene","Ethylhexyl Salicylate","Butyl Methoxydibenzoylmethane","Drometrizole Trisiloxane","Dimethicone","Glycerin","Aloe Barbadensis Leaf Juice","Tocopherol"],"match_score":81,"reason":"Very high SPF 100 protection in a cosmetically elegant milk format — offers reliable daily UV defense though the chemical filter blend may irritate ultra-sensitive skin.","concern_flag":"Contains Fragrance","attributes":["Water-Resistant","Non-Comedogenic"],"concern_flags":["Contains Fragrance"],"ai_reason":"Very high SPF 100 protection in a cosmetically elegant milk format — offers reliable daily UV defense though the chemical filter blend may irritate ultra-sensitive skin."},
  {"name":"Natural Moisturizing Factors + HA","brand":"THE ORDINARY","category":"Moisturizers","price":12.99,"ingredients":["Aqua","Caprylic/Capric Triglyceride","Cetearyl Alcohol","Glycerin","Sodium Hyaluronate","Arginine","Urea","Ceramide NP","Ceramide AP","Palmitic Acid","Linoleic Acid","Allantoin","Panthenol"],"match_score":83,"reason":"Comprehensive moisturizer duplicating the skin's Natural Moisturizing Factors with Amino Acids and Ceramides — basic but effective maintenance for normal skin.","concern_flag":null,"attributes":["Fragrance-Free","Alcohol-Free","Vegan","Cruelty-Free"],"concern_flags":[],"ai_reason":"Comprehensive moisturizer duplicating the skin's Natural Moisturizing Factors with Amino Acids and Ceramides — basic but effective maintenance for normal skin."},
  {"name":"Creamy Jelly Cleanser","brand":"BYOMA","category":"Cleansers","price":19.99,"ingredients":["Aqua","Glycerin","Coco-Glucoside","Cocamidopropyl Betaine","Squalane","Ceramide NP","Ceramide AP","Panthenol","Allantoin","Aloe Barbadensis Leaf Juice"],"match_score":86,"reason":"Squalane-based cream cleanser with Ceramides and Panthenol supports the moisture barrier while cleansing effectively — ideal for dry, dehydrated, or sensitive skin.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Vegan"],"concern_flags":[],"ai_reason":"Squalane-based cream cleanser with Ceramides and Panthenol supports the moisture barrier while cleansing effectively — ideal for dry, dehydrated, or sensitive skin."},
  {"name":"Probiotic Skin Care Ultra Hydrating Day & Night Cream","brand":"TULA","category":"Moisturizers","price":49.99,"ingredients":["Aqua","Glycerin","Caprylic/Capric Triglyceride","Cetyl Alcohol","Lactobacillus Ferment","Squalane","Sodium Hyaluronate","Niacinamide","Ceramide NP","Tocopherol","Panthenol"],"match_score":79,"reason":"Probiotic ferment supports a healthy skin microbiome while Squalane and Ceramides moisturize — beneficial for balance but the price is premium for standard actives.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Probiotic ferment supports a healthy skin microbiome while Squalane and Ceramides moisturize — beneficial for balance but the price is premium for standard actives."},
  {"name":"Salicylic Acid + Tea Tree Body Wash","brand":"AUCHAN","category":"Cleansers","price":9.99,"ingredients":["Aqua","Sodium Laureth Sulfate","Cocamidopropyl Betaine","Salicylic Acid","Melaleuca Alternifolia Leaf Oil","Glycerin","Panthenol","Citric Acid"],"match_score":70,"reason":"Effective body cleanser for chest and back acne with Salicylic Acid and Tea Tree Oil, though high sulfate content may be overly stripping for facial use.","concern_flag":"Contains Sulfates","attributes":["Paraben-Free"],"concern_flags":["Contains Sulfates","Contains Fragrance"],"ai_reason":"Effective body cleanser for chest and back acne with Salicylic Acid and Tea Tree Oil, though high sulfate content may be overly stripping for facial use."},
  {"name":"Clearly Corrective Dark Spot Solution","brand":"KIEHL'S","category":"Treatment","price":55.99,"ingredients":["Aqua","Ascorbyl Glucoside","Dimethicone","Glycerin","Salicylic Acid","Paeonia Suffruticosa Root Extract","Sodium Hyaluronate","Phenoxyethanol"],"match_score":87,"reason":"Activated Vitamin C derivative combined with Peony extract targets dark spots and uneven tone with gradual, visible improvement over consistent use.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic"],"concern_flags":[],"ai_reason":"Activated Vitamin C derivative combined with Peony extract targets dark spots and uneven tone with gradual, visible improvement over consistent use."},
  {"name":"Moisturizing Cream","brand":"VANICREAM","category":"Moisturizers","price":14.99,"ingredients":["Aqua","Petrolatum","Cetearyl Alcohol","Propylene Glycol","Cetyl Alcohol","Dimethicone","Glyceryl Stearate","Stearic Acid","Beeswax","Tocopherol"],"match_score":94,"reason":"Free of virtually every common irritant (fragrance, dyes, lanolin, parabens, formaldehyde) — clinically proven for even the most reactive, allergy-prone skin.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Formaldehyde-Free","Lanolin-Free"],"concern_flags":[],"ai_reason":"Free of virtually every common irritant (fragrance, dyes, lanolin, parabens, formaldehyde) — clinically proven for even the most reactive, allergy-prone skin."},
  {"name":"Universal Tinted Moisturizer SPF 46","brand":"DRMTLGY","category":"Sunscreen","price":38.99,"ingredients":["Aqua","Zinc Oxide","Titanium Dioxide","Aloe Barbadensis Leaf Juice","Glycerin","Coconut Alkanes","Coco-Caprylate","Tocopherol","Panthenol","Iron Oxides"],"match_score":92,"reason":"Mineral tinted SPF with adaptive color technology provides sheer coverage while Zinc Oxide protects — a daily multi-tasker that replaces both sunscreen and light foundation.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic","Vegan"],"concern_flags":[],"ai_reason":"Mineral tinted SPF with adaptive color technology provides sheer coverage while Zinc Oxide protects — a daily multi-tasker that replaces both sunscreen and light foundation."},
  {"name":"Glass Skin Refining Serum","brand":"PEACH & LILY","category":"Treatment","price":39.99,"ingredients":["Aqua","Propanediol","Glycerin","Niacinamide","Sodium Hyaluronate","Betaine","Phenoxyethanol","Panthenol","Arginine","Aloe Barbadensis Leaf Juice"],"match_score":81,"reason":"Peptide-infused serum with Niacinamide and multiple molecular weights of Hyaluronic Acid creates a plumping, glass-like finish — good for general luminosity.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Peptide-infused serum with Niacinamide and multiple molecular weights of Hyaluronic Acid creates a plumping, glass-like finish — good for general luminosity."},
  {"name":"Calm + Restore Nourishing Oat Cleanser","brand":"AVEENO","category":"Cleansers","price":15.99,"ingredients":["Aqua","Glycerin","Cetearyl Alcohol","Avena Sativa Kernel Flour","Caprylic/Capric Triglyceride","Cetyl Alcohol","Stearyl Alcohol","Ceramide NP","Cholesterol","Panthenol","Allantoin"],"match_score":93,"reason":"Prebiotic colloidal oatmeal physically calms irritation while Ceramides restore the barrier — clinically shown to reduce redness in sensitive skin conditions like eczema.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic"],"concern_flags":[],"ai_reason":"Prebiotic colloidal oatmeal physically calms irritation while Ceramides restore the barrier — clinically shown to reduce redness in sensitive skin conditions like eczema."},
  {"name":"Toleriane Purifying Foaming Face Wash","brand":"LA ROCHE-POSAY","category":"Cleansers","price":16.99,"ingredients":["Aqua","Glycerin","Cocamidopropyl Betaine","Sodium Cocoyl Glycinate","Peg-120 Methyl Glucose Dioleate","Niacinamide","Zinc PCA","Ceramide NP","Panthenol"],"match_score":96,"reason":"Niacinamide and Zinc PCA in a gentle foaming cleanser purge excess oil without stripping the barrier — specifically formulated for oily, blemish-prone sensitive skin.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Soap-Free"],"concern_flags":[],"ai_reason":"Niacinamide and Zinc PCA in a gentle foaming cleanser purge excess oil without stripping the barrier — specifically formulated for oily, blemish-prone sensitive skin."},
  {"name":"Daily UV Defense SPF 36","brand":"INNISFREE","category":"Sunscreen","price":19.99,"ingredients":["Aqua","Zinc Oxide","Dimethicone","C12-15 Alkyl Benzoate","Cetyl Ethylhexanoate","Glycerin","Cetearyl Alcohol","Camellia Sinensis Seed Oil","Tocopherol"],"match_score":83,"reason":"Lightweight mineral SPF with Green Tea Seed Oil providing antioxidant protection — a decent daily sunscreen but SPF 36 is lower than recommended for prolonged sun exposure.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Lightweight mineral SPF with Green Tea Seed Oil providing antioxidant protection — a decent daily sunscreen but SPF 36 is lower than recommended for prolonged sun exposure."},
  {"name":"Ultimate Nourishing Rice Overnight Spa Mask","brand":"COSRX","category":"Moisturizers","price":17.99,"ingredients":["Aqua","Glycerin","Cetearyl Alcohol","Oryza Sativa Bran Water","Butylene Glycol","Caprylic/Capric Triglyceride","Niacinamide","Stearic Acid","Panthenol","Allantoin"],"match_score":78,"reason":"Rice Bran Water and Niacinamide provide brightening and nourishing benefits in a sleeping mask format — a complementary product but not a standalone moisturizer.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Rice Bran Water and Niacinamide provide brightening and nourishing benefits in a sleeping mask format — a complementary product but not a standalone moisturizer."},
  {"name":"Protini Polypeptide Moisturizer","brand":"DRUNK ELEPHANT","category":"Moisturizers","price":66.99,"ingredients":["Aqua","Glycerin","Squalane","Cetearyl Alcohol","Caprylic/Capric Triglyceride","Palmitoyl Tripeptide-1","Palmitoyl Tetrapeptide-7","Sodium Hyaluronate","Niacinamide","Ceramide NP","Panthenol"],"match_score":86,"reason":"Signal peptides (Tripeptide-1, Tetrapeptide-7) stimulate collagen production while Squalane and Ceramides moisturize — excellent for anti-aging and barrier maintenance.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","Silicone-Free"],"concern_flags":[],"ai_reason":"Signal peptides (Tripeptide-1, Tetrapeptide-7) stimulate collagen production while Squalane and Ceramides moisturize — excellent for anti-aging and barrier maintenance."},
  {"name":"Mineral Sunscreen SPF 50","brand":"PIPETTE","category":"Sunscreen","price":13.99,"ingredients":["Zinc Oxide","Caprylic/Capric Triglyceride","Coconut Alkanes","Coco-Caprylate","Polyglyceryl-6 Polyhydroxystearate","Tocopherol","Panthenol","Helianthus Annuus Seed Oil"],"match_score":88,"reason":"Clean mineral SPF formula with a short, understandable ingredient list — Zinc Oxide as the single active filter is gentle yet effective for daily face protection.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Vegan","Cruelty-Free"],"concern_flags":[],"ai_reason":"Clean mineral SPF formula with a short, understandable ingredient list — Zinc Oxide as the single active filter is gentle yet effective for daily face protection."},
  {"name":"AHA-BHA-PHA 30 Days Miracle Toner","brand":"SOME BY MI","category":"Treatment","price":19.99,"ingredients":["Aqua","Butylene Glycol","Niacinamide","Salicylic Acid","Lactobionic Acid","Melaleuca Alternifolia Leaf Water","Centella Asiatica Extract","Panthenol","Sodium Hyaluronate"],"match_score":71,"reason":"Triple-acid toner (AHA, BHA, PHA) provides comprehensive exfoliation but may overwhelm very sensitive or newly-treated skin — best for experienced acid users.","concern_flag":"Contains Fragrance","attributes":["Paraben-Free","Cruelty-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"Triple-acid toner (AHA, BHA, PHA) provides comprehensive exfoliation but may overwhelm very sensitive or newly-treated skin — best for experienced acid users."},
  {"name":"Hydra Vizor Invisible Moisturizer SPF 30","brand":"FENTY SKIN","category":"Sunscreen","price":35.99,"ingredients":["Aqua","Dimethicone","Homosalate","Octocrylene","Glycerin","Niacinamide","Ethylhexyl Salicylate","Butyl Methoxydibenzoylmethane","Squalane","Panthenol","Hyaluronic Acid"],"match_score":84,"reason":"SPF 30 and Niacinamide in a sheer, universally-tinted moisturizer that works on all skin tones — good daily protection with a natural finish.","concern_flag":"Contains Fragrance","attributes":["Non-Comedogenic","Paraben-Free"],"concern_flags":["Contains Fragrance"],"ai_reason":"SPF 30 and Niacinamide in a sheer, universally-tinted moisturizer that works on all skin tones — good daily protection with a natural finish."},
  {"name":"Aloe BHA Skin Toner","brand":"BENTON","category":"Treatment","price":15.99,"ingredients":["Aloe Barbadensis Leaf Water","Aqua","Butylene Glycol","Snail Secretion Filtrate","Salicylic Acid","Betaine","Sodium Hyaluronate","Panthenol","Allantoin","Camellia Sinensis Leaf Extract"],"match_score":82,"reason":"Aloe-based toner with 0.5% Salicylic Acid and Snail Mucin provides gentle exfoliation alongside soothing hydration — a balanced option for combination acne-prone skin.","concern_flag":null,"attributes":["Paraben-Free","Cruelty-Free","Vegan"],"concern_flags":[],"ai_reason":"Aloe-based toner with 0.5% Salicylic Acid and Snail Mucin provides gentle exfoliation alongside soothing hydration — a balanced option for combination acne-prone skin."},
  {"name":"Ultra Repair Cream Intense Hydration","brand":"FIRST AID BEAUTY","category":"Moisturizers","price":38.99,"ingredients":["Aqua","Glycerin","Caprylic/Capric Triglyceride","Glyceryl Stearate","Cetearyl Alcohol","Colloidal Oatmeal","Shea Butter","Ceramide NP","Squalane","Allantoin","Panthenol","Licorice Root Extract"],"match_score":95,"reason":"Colloidal Oatmeal and Shea Butter provide immediate relief for dry, irritated skin while Ceramides and Squalane lock in moisture for up to 24 hours.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Cruelty-Free","For Sensitive Skin"],"concern_flags":[],"ai_reason":"Colloidal Oatmeal and Shea Butter provide immediate relief for dry, irritated skin while Ceramides and Squalane lock in moisture for up to 24 hours."},
  {"name":"Cicalfate+ Restorative Protective Cream","brand":"AVENE","category":"Moisturizers","price":29.99,"ingredients":["Aqua","Mineral Oil","Glycerin","Zinc Oxide","Copper Sulfate","Zinc Sulfate","Calcium Alginate","Petrolatum","Stearyl Alcohol","Beeswax"],"match_score":89,"reason":"Post-biotic Avène Thermal Water combined with Copper-Zinc sulfate complex creates an optimal healing environment for compromised skin — ideal post-procedure or for active rashes.","concern_flag":null,"attributes":["Fragrance-Free","Paraben-Free","Non-Comedogenic"],"concern_flags":[],"ai_reason":"Post-biotic Avène Thermal Water combined with Copper-Zinc sulfate complex creates an optimal healing environment for compromised skin — ideal post-procedure or for active rashes."},
];

const LOOKUP: Record<string, number[]> = {
  "acne scars": [4, 16, 28, 44, 47, 8, 48, 49, 5, 39],
  "pimples":    [0, 2, 3, 22, 40, 34, 13, 27, 25, 12],
  "acne":       [1, 11, 15, 7, 17, 24, 26, 30, 37, 31],
  "pigmentation": [9, 28, 38, 10, 33, 18, 35, 19, 42, 43],
  "redness":    [14, 23, 20, 6, 36, 21, 41, 44, 46, 32],
};

export const LOOKUP_KEYS = Object.keys(LOOKUP);

function pick(indices: number[]): MarketplaceProduct[] {
  return indices.map(i => ({
    name: allProducts[i].name, brand: allProducts[i].brand, reason: allProducts[i].reason,
    concern_flag: allProducts[i].concern_flag, match_score: allProducts[i].match_score, price: allProducts[i].price,
  }));
}

export function getMockMarketplaceSearch(goal: string): MarketplaceProduct[] {
  const q = goal.toLowerCase().trim();

  if (!q) {
    return [...allProducts]
      .sort((a, b) => b.match_score - a.match_score)
      .slice(0, 8)
      .map(p => ({
        name: p.name, brand: p.brand, reason: p.reason,
        concern_flag: p.concern_flag, match_score: p.match_score, price: p.price,
      }));
  }

  if (LOOKUP[q]) return pick(LOOKUP[q]);

  const found = Object.keys(LOOKUP).find(k => k.includes(q) || q.includes(k));
  if (found) return pick(LOOKUP[found]);

  return Object.values(LOOKUP).flatMap(indices => pick(indices));
}

export function getAllMockProducts() {
  return allProducts;
}
